expcriativa/controllers/actuator_controller.py
#controllers.actuator_controller.py
from flask import Blueprint, request, render_template, redirect, url_for
from models.iot.actuators import Actuator
from utils.decorators import *


actuator_ = Blueprint("Actuator_", __name__, template_folder="templates")

@actuator_.route('/register_atuador')
@role_required('admin', 'operador', 'estatistico')
def register_actuator():
    return render_template("register_atuador.html")


@actuator_.route('/add_actuator', methods = ['POST'])
@role_required('admin', 'operador', 'estatistico')
def add_actuator():
    name = request.form.get("name")
    brand = request.form.get("brand")
    model = request.form.get("model")
    topic = request.form.get("topic")
    unit = request.form.get("unit")
    is_active = True if request.form.get("is_active") == "on" else False

    Actuator.save_actuator(name, brand, model, topic, unit, is_active )

    actuators = Actuator.get_actuators()
    return render_template("atuadores.html", actuators = actuators)

@actuator_.route('/list_actuators')
@role_required('admin', 'operador', 'estatistico')
def actuators():
    actuators = Actuator.get_actuators()
    return render_template("atuadores.html", actuators = actuators)

@actuator_.route('/edit_actuator')
@role_required('admin', 'operador', 'estatistico')
def edit_actuator():
    id = request.args.get('id', None)
    actuator = Actuator.get_single_actuator(id)
    return render_template("update_actuator.html", actuator = actuator)

@actuator_.route('/update_actuator', methods=['POST'])
@role_required('admin', 'operador', 'estatistico')
def update_actuator():
    id = request.form.get("id")
    name = request.form.get("name")
    brand = request.form.get("brand")
    model = request.form.get("model")
    topic = request.form.get("topic")
    unit = request.form.get("unit")
    is_active = True if request.form.get("is_active") == "on" else False
    actuator = Actuator.update_actuator(id, name, brand, model, topic, unit, is_active )
    return render_template("atuadores.html", actuator = actuator)

@actuator_.route('/del_actuator', methods=['GET'])
@role_required('admin', 'operador', 'estatistico')
def del_actuator():
    id = request.args.get('id', None)
    actuator = Actuator.delete_actuator(id)
    return render_template("atuadores.html", actuator = actuator)

expcriativa/controllers/auth_controller.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user, login_required
from models.db import db
from models.user.user import User

auth_ = Blueprint('auth', __name__, template_folder="templates")


@auth_.route("/add_user", methods=["GET", "POST"])
def add_user():
    if request.method == "POST":
        username = request.form["username"]
        email = request.form["email"]
        senha = request.form["senha"]
        roles = request.form.getlist("roles")  # <- Captura os perfis selecionados

        # Verifica se já existe username ou email
        if User.query.filter((User.username == username) | (User.email == email)).first():
            return render_template("register_user.html", erro="Usuário ou email já cadastrado")

        # Se for o primeiro usuário, adiciona automaticamente o papel admin
        #if User.query.count() == 0 and "admin" not in roles:
        #    roles.append("admin")

        novo_usuario = User(
            username=username,
            email=email,
            roles=",".join(roles)
        )
        novo_usuario.set_senha(senha)

        db.session.add(novo_usuario)
        db.session.commit()

        return redirect(url_for("user_.home"))

    return render_template("register_user.html")


@auth_.route("/validate_user", methods=["POST"])
def validated_user():
    username = request.form["username"]
    senha = request.form["senha"]
    user = User.query.filter_by(username=username).first()

    if user and user.verificar_senha(senha):
        login_user(user)  
        return redirect(url_for("user_.home"))

    return render_template("login.html", erro="Usuário ou senha inválidos")


@auth_.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("user_.login"))

expcriativa/controllers/sensor_controller.py
#sensors_controller.py
from flask import Blueprint, request, render_template, redirect, url_for
from models.iot.sensors import Sensor
from utils.decorators import *


sensor_ = Blueprint("sensor_",__name__, template_folder="templates")

@sensor_.route('/register_sensor')
@role_required('admin', 'operador', 'estatistico')
def register_sensor():
    return render_template("register_sensor.html")

@sensor_.route('/add_sensor', methods=['POST'])
@role_required('admin', 'operador', 'estatistico')
def add_sensor():
    name = request.form.get("name")
    brand = request.form.get("brand")
    model = request.form.get("model")
    topic = request.form.get("topic")
    unit = request.form.get("unit")
    is_active = True if request.form.get("is_active") == "on" else False

    Sensor.save_sensor(name, brand, model, topic, unit, is_active )

    sensors = Sensor.get_sensors()
    return render_template("sensors.html")

@sensor_.route('/list_sensors')
@role_required('admin', 'operador', 'estatistico')
def sensors():
    sensors = Sensor.get_sensors()
    return render_template("sensors.html", sensors = sensors)

@sensor_.route('/edit_sensor')
@role_required('admin', 'operador', 'estatistico')
def edit_sensor():
    id = request.args.get('id', None)
    sensor = Sensor.get_single_sensor(id)
    return render_template("update_sensor.html", sensor = sensor)

@sensor_.route('/update_sensor', methods=['POST'])
@role_required('admin', 'operador', 'estatistico')
def update_sensor():
    id = request.form.get("id")
    name = request.form.get("name")
    brand = request.form.get("brand")
    model = request.form.get("model")
    topic = request.form.get("topic")
    unit = request.form.get("unit")
    is_active = True if request.form.get("is_active") == "on" else False
    sensors = Sensor.update_sensor(id, name, brand, model, topic, unit, is_active )
    return render_template("sensors.html", sensors = sensors)

@sensor_.route('/del_sensor', methods=['GET'])
@role_required('admin', 'operador', 'estatistico')
def del_sensor():
    id = request.args.get('id', None)
    sensors = Sensor.delete_sensor(id)
    return render_template("sensors.html", sensors = sensors)




expcriativa/controllers/user_controller.py
#user_controller.py
from flask import Blueprint, request, render_template, redirect, url_for
from models.user.user import User
from utils.decorators import *
from models.db import *


user_ = Blueprint("user_",__name__, template_folder="templates")



@user_.route('/home')
@login_required_custom
def home():
    return render_template('home.html')

@user_.route('/login')
def login():
    return render_template('login.html')

@user_.route('/register_user')
def register_user():
    return render_template("register_user.html")

@user_.route('/list_users')
@role_required('admin', 'operador', 'estatistico')
def list_user():
    users = User.query.all()  # lista de objetos User
    return render_template("user.html", users=users)


@user_.route('/edit_user/<int:user_id>', methods=["GET", "POST"])
@role_required('admin', 'operador', 'estatistico')
def edit_user(user_id):
    user = User.query.get_or_404(user_id)
    
    if request.method == "POST":
        user.username = request.form["username"]
        user.email = request.form["email"]
        user.roles = ",".join(request.form.getlist("roles"))

        nova_senha = request.form.get("senha")
        if nova_senha:
            user.set_senha(nova_senha)

        db.session.commit()
        return redirect(url_for('user_.list_user'))

    return render_template("edit_user.html", user=user)

@user_.route('/delete_user/<int:user_id>', methods=["POST"])
@role_required('admin', 'operador', 'estatistico')
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('user_.list_user'))




expcriativa/templates/atuadores.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Lista de Atuadores</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/listar_atuador.css') }}">
</head>

<body>
        <header class="main-header">
        {% if current_user.is_authenticated %}
            <div class="user-info-wrapper">
                <p>Olá, <strong>{{ current_user.username }}</strong>!</p>

                <div class="roles-and-logout">
                    {% if current_user.has_role('admin') %}
                        <span>Admin</span>
                    {% endif %}
                    {% if current_user.has_role('estatistico') %}
                        <span>Estatístico</span>
                    {% endif %}
                    {% if current_user.has_role('operador') %}
                        <span>Operador</span>
                    {% endif %}

                    <a class="logout-button" href="{{ url_for('auth.logout') }}">Sair</a>
                </div>
            </div>
        {% else %}
            <nav>
                <a href="{{ url_for('user_.login') }}">Login</a>
            </nav>
        {% endif %}
    </header>
    
    <main>
        <h1 class="titulo">Atuadores Cadastrados</h1>

        <div class="login-card">
            {% if actuators|length > 0 %}
                <table class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Marca</th>
                            <th>Modelo</th>
                            <th>Tópico</th>
                            <th>Unidade</th>
                            <th>Ativo?</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for actuator in actuators %}
                            <tr>
                                <td>{{ actuator.name }}</td>
                                <td>{{ actuator.brand }}</td>
                                <td>{{ actuator.model }}</td>
                                <td>{{ actuator.topic }}</td> 
                                <td>{{ actuator.unit }}</td>
                                <td>
                                    {% if actuator.is_active %}
                                        Ativo
                                    {% else %}
                                        Desativado
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="http://localhost:8080/edit_actuator?id={{ actuator.id }}">Editar</a> |
                                    <a href="http://localhost:8080/del_actuator?id={{ actuator.id }}">Deletar</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>Nenhum atuador cadastrado até o momento.</p>
            {% endif %}
        </div>

        <nav>
            <form action="http://localhost:8080/register_atuador" style="display: inline;">
                <input type="submit" value="Cadastrar Novo Atuador" />
            </form>
            <form action="http://localhost:8080/home" style="display: inline;">
                <input type="submit" value="Voltar ao Início" />
            </form>
        </nav>
    </main>
</body>
</html>


expcriativa/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Minha Aplicação{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block head_extra %}{% endblock %}
</head>
<body>
    <header class="main-header">
        {% if current_user.is_authenticated %}
            <div class="user-info-wrapper">
                <p>Olá, <strong>{{ current_user.username }}</strong>!</p>

                <div class="roles-and-logout">
                    {% if current_user.has_role('admin') %}
                        <span>Admin</span>
                    {% endif %}
                    {% if current_user.has_role('estatistico') %}
                        <span>Estatístico</span>
                    {% endif %}
                    {% if current_user.has_role('operador') %}
                        <span>Operador</span>
                    {% endif %}

                    <a class="logout-button" href="{{ url_for('auth.logout') }}">Sair</a>
                </div>
            </div>
        {% else %}
            <nav>
                <a href="{{ url_for('user_.login') }}">Login</a>
            </nav>
        {% endif %}
    </header>




    <main>
        <div class="sidebar">
            <a href="/home" class="home-icon-wrapper">
                <img src="{{ url_for('static', filename='img/icon-home.png') }}" class="sidebar-icon">
                <label>Home</label>
            </a>
            
            <a href="javascript:history.back()" class="back-button">
                <img src="{{ url_for('static', filename='img/voltar.png') }}" class="sidebar-icon">
                <label>Back</label>
            </a>
    </div>
        {% block content %}{% endblock %}
    </main>

    {% block scripts %}
        <!-- JS comuns a todas as páginas -->
    {% endblock %}
</body>
</html>


expcriativa/templates/edit_user.html
<!--edit_user.html -->
{% extends"base.html" %}
{% block content%} 
    <h1 class="edit-user-a">Editar Usuário</h1>
    <div class="edit-user">
        <form method="POST">
            <label for="username">Nome de Usuário:</label><br>
            <input type="text" id="username" name="username" value="{{ user.username }}" required><br><br>

            <label for="email">Email:</label><br>
            <input type="email" id="email" name="email" value="{{ user.email }}" required><br><br>

            <label for="roles">Funções (separadas por vírgula):</label><br>
            <input type="text" id="roles" name="roles" value="{{ user.roles }}"><br><br>

            <label for="senha">Nova Senha (opcional):</label><br>
            <input type="password" id="senha" name="senha"><br><br>

            <button type="submit">Salvar Alterações</button>
        </form>

        <br>
        <form action="http://localhost:8080/list_users">
             <input type="submit" value="Voltar">
        </form>
    </div>
{% endblock%}


expcriativa/templates/history_write.html
<!--history_write.html -->
{% extends"base.html" %}
{% block content%} 
<div class="vertical-center">
    <div class="container">
        <div class="card-history">
            <div class="card-header">
                <div class="card-body">
                    <form action="http://localhost:8080/get_write" method="post">
                        <select name="id" class="Input" required>
                            {% if actuators|length == 0 %}
                                <option value="" disabled selected>Sem atuadores disponíveis</option>
                            {% else %}
                                {% for actuator in actuators %}
                                    <option value="{{ actuator.id }}">{{ actuator.name }}</option>
                                {% endfor %}
                            {% endif %}
                        </select>                        
                        <p></p>
                        <p></p>
                        <p></p>
                        Início:
                        <p><input type="datetime-local"  name="start" required/></p>
                        Fim:
                        <p><input type="datetime-local"  name="end" required/></p>
                        <input type="submit" value="Carregar" class="btn btn-primary" />
                    </form>
                    {% if write|length> 0 %}
                        <table id="view_write" class="table table-striped table-bordered" style="width:100%">
                            <p>Atuações:</p>
                            <thead>
                                <tr>
                                    <th>Atuador</th>
                                    <th>Valor</th>
                                    <th>Horário</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for write in write %}
                                    <tr>
                                        <td>{{ write.actuators_id }}</td>
                                        <td>{{ write.value }}</td>
                                        <td>{{ write.write_datetime }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% endif %} 
                </div>
            </div>
        </div>
    </div>
</div>   
{% endblock%}

expcriativa/templates/home.html
{% extends "base.html" %}

{% block title %}Painel Admin{% endblock %}

{% block content %}
<div class="layout">
    <!--
    <div class="sidebar">
        <a href="/home" class="home-icon-wrapper">
            <img src="{{ url_for('static', filename='img/icon-home.png') }}" class="sidebar-icon">
            <label>Home</label>
        </a>
        
        <a href="/" class="back-button">
            <img src="{{ url_for('static', filename='img/voltar.png') }}" class="sidebar-icon">
            <label>Back</label>
        </a>
    </div>
-->
    <div class="main-content">
        {% if current_user.has_role('operador') or current_user.has_role('admin') %}
        <a href="/publish" class="card-link">
            <div class="card">
                <p>Publicar dados</p>
            </div>
        </a>
        {% endif %}
        {% if current_user.has_role('estatistico') or current_user.has_role('admin') %}
        <a href="/tr" class="card-link">
            <div class="card">
                <p>Visualizar Tempo Real</p>
            </div>
        </a>
        {% endif %}
    </div>    
</div>

{% if current_user.has_role('admin') or current_user.has_role('estatistico') or current_user.has_role('operador')%}
<div class="admin-dropdown">
    <button class="admin-toggle" type="button">
        <img src="{{ url_for('static', filename='img/icon-config.png') }}" alt="Admin">
    </button>
    <div class="admin-menu-content">
        <a href="/register_user">Cadastrar Usuários</a>
        <a href="/register_sensor">Cadastrar Sensores</a>
        <a href="/register_atuador">Cadastrar Atuadores</a>
        <a href="/list_users">Listar Usuários</a>
        <a href="/list_sensors">Listar Sensores</a>
        <a href="/list_actuators">Listar Atuadores</a>
        <a href="/history_read">Historico de Dados</a>
        <a href="/history_write">Historico de Atuaçoes</a>
    </div>
</div>
{% endif %}
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='admin.js') }}" defer></script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const dropdown = document.querySelector(".admin-dropdown");
        const toggle = document.querySelector(".admin-toggle");

        if (dropdown && toggle) {
            toggle.addEventListener("click", () => {
                dropdown.classList.toggle("open");
            });

            window.addEventListener("click", (e) => {
                if (!dropdown.contains(e.target) && !toggle.contains(e.target)) {
                    dropdown.classList.remove("open");
                }
            });
        }
    });
</script>
{% endblock %}

expcriativa/templates/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body>
    <h2 class="titulo">Sign in</h2>
    <div class="login-card">
        <form action="{{ url_for('auth.validated_user') }}" method="post">
            <input type="text" name="username" placeholder="Usuário" required>
            <input type="password" name="senha" placeholder="Senha" required>
            <button type="submit">Entrar</button>
            <p>Ainda não tem conta?</p>
            <a href="{{ url_for('user_.register_user') }}">Criar nova conta</a>
        </form>        
    </div>
</body>
</html>

expcriativa/templates/register_atuador.html
<html>
    <head>
        <meta charset="UTF-8">
        <title>Cadastro de Sensor/Atuador</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/register_atuador.css') }}">
    </head>
    <body>
        <header class="main-header">
            {% if current_user.is_authenticated %}
                <div class="user-info-wrapper">
                    <p>Olá, <strong>{{ current_user.username }}</strong>!</p>

                    <div class="roles-and-logout">
                        {% if current_user.has_role('admin') %}
                            <span>Admin</span>
                        {% endif %}
                        {% if current_user.has_role('estatistico') %}
                            <span>Estatístico</span>
                        {% endif %}
                        {% if current_user.has_role('operador') %}
                            <span>Operador</span>
                        {% endif %}

                        <a class="logout-button" href="{{ url_for('auth.logout') }}">Sair</a>
                    </div>
                </div>
            {% else %}
                <nav>
                    <a href="{{ url_for('user_.login') }}">Login</a>
                </nav>
            {% endif %}
        </header>


        <main>
            <h2 class="titulo">Cadastrar Novo Dispositivo</h2>
            
            <div class="login-card">
                <h3 class="form-title">Cadastrar Atuador</h3>
                <form action="{{ url_for('Actuator_.add_actuator') }}" method="post">
                    <input type="text" name="name" placeholder="Nome do Atuador" required />
                    <input type="text" name="brand" placeholder="Marca do Atuador" required />
                    <input type="text" name="model" placeholder="Modelo do Atuador" required />
                    <input type="number" name="unit" placeholder="Unidades" required />
                    <input type="text" name="topic" placeholder="Topico MQTT" value="/irrigar/controle" required />
                    <div>
                        <input type="checkbox" id="is_active" name="is_active" checked />
                        <label for="is_active">Ativo?</label>
                    </div>
                    <div class="btn-wrapper">
                        <button type="submit">Cadastrar Atuador</button>
                        <a href="/home" class="btn-voltar">Voltar ao Início</a>
                    </div>
                </form> 
            </div>
        </main>
    </body>
</html>

expcriativa/templates/register_user.html
<html>
<head>
    <meta charset="UTF-8">
    <title>Cadastrar Novo Usuário</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register_user.css') }}">
</head>
<body>
            <header class="main-header">
        {% if current_user.is_authenticated %}
            <div class="user-info-wrapper">
                <p>Olá, <strong>{{ current_user.username }}</strong>!</p>

                <div class="roles-and-logout">
                    {% if current_user.has_role('admin') %}
                        <span>Admin</span>
                    {% endif %}
                    {% if current_user.has_role('estatistico') %}
                        <span>Estatístico</span>
                    {% endif %}
                    {% if current_user.has_role('operador') %}
                        <span>Operador</span>
                    {% endif %}

                    <a class="logout-button" href="{{ url_for('auth.logout') }}">Sair</a>
                </div>
            </div>
        {% else %}
            <nav>
                <a href="{{ url_for('user_.login') }}">Login</a>
            </nav>
        {% endif %}
    </header>

    
    <main>
        <h2 class="titulo">Cadastrar Novo Usuário</h2>
        <div class="login-card">
            {% if erro %}
                <p style="color:red">{{ erro }}</p>
            {% endif %}
            <form action="{{ url_for('auth.add_user') }}" method="post">
                <input type="text" name="username" placeholder="Nome de usuário" required />
                <input type="email" name="email" placeholder="E-mail" required />
                <input type="password" name="senha" placeholder="Senha" required />
                <label>Perfis de acesso:</label><br>
                <input type="checkbox" name="roles" value="admin"> Admin<br>
                <input type="checkbox" name="roles" value="estatistico"> Estatístico<br>
                <input type="checkbox" name="roles" value="operador"> Operador<br>

                <button type="submit">Cadastrar</button>
            </form>
            <a href="/home" class="standard-btn">Voltar ao Início</a>
        </div>
    </main>
</body>
</html>


expcriativa/templates/remove_user.html
<html>
<head>
    <meta charset="UTF-8">
    <title>Deletar Usuário</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/delete_user.css') }}">
</head>
<body>
            <header class="main-header">
        {% if current_user.is_authenticated %}
            <div class="user-info-wrapper">
                <p>Olá, <strong>{{ current_user.username }}</strong>!</p>

                <div class="roles-and-logout">
                    {% if current_user.has_role('admin') %}
                        <span>Admin</span>
                    {% endif %}
                    {% if current_user.has_role('estatistico') %}
                        <span>Estatístico</span>
                    {% endif %}
                    {% if current_user.has_role('operador') %}
                        <span>Operador</span>
                    {% endif %}

                    <a class="logout-button" href="{{ url_for('auth.logout') }}">Sair</a>
                </div>
            </div>
        {% else %}
            <nav>
                <a href="{{ url_for('user_.login') }}">Login</a>
            </nav>
        {% endif %}
    </header>
    <h2>Deletar Usuário</h2>
    <div class="delete-card">
        <form action="http://localhost:8080/del_user" method="post">
            <select name="user">
                {% for key, value in devices.items() %}
                <option value="{{ key }}">{{ key }}</option>
                {% endfor %}
            </select>
            <input type="submit" value="Deletar" />
        </form>
    </div>
    <a href="/home">Voltar ao Início</a>
</body>
</html>

expcriativa/templates/sensors.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Lista de Atuadores</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/listar_sensor.css') }}">
</head>
<body>
            <header class="main-header">
        {% if current_user.is_authenticated %}
            <div class="user-info-wrapper">
                <p>Olá, <strong>{{ current_user.username }}</strong>!</p>

                <div class="roles-and-logout">
                    {% if current_user.has_role('admin') %}
                        <span>Admin</span>
                    {% endif %}
                    {% if current_user.has_role('estatistico') %}
                        <span>Estatístico</span>
                    {% endif %}
                    {% if current_user.has_role('operador') %}
                        <span>Operador</span>
                    {% endif %}

                    <a class="logout-button" href="{{ url_for('auth.logout') }}">Sair</a>
                </div>
            </div>
        {% else %}
            <nav>
                <a href="{{ url_for('user_.login') }}">Login</a>
            </nav>
        {% endif %}
    </header>

    <main>
        <h1 class="titulo">Sensores Cadastrados</h1>

        <div class="login-card">
            {% if sensors|length > 0 %}
                <table class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Marca</th>
                            <th>Modelo</th>
                            <th>Tópico</th>
                            <th>Unidade</th>
                            <th>Ativo?</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for sensor in sensors %}
                            <tr>
                                <td>{{ sensor.name }}</td>
                                <td>{{ sensor.brand }}</td>
                                <td>{{ sensor.model }}</td>
                                <td>{{ sensor.topic }}</td> 
                                <td>{{ sensor.unit }}</td>
                                <td>
                                    {% if sensor.is_active %}
                                        Ativo
                                    {% else %}
                                        Desativado
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="http://localhost:8080/edit_sensor?id={{ sensor.id }}">Editar</a>
                                    <a href="http://localhost:8080/del_sensor?id={{ sensor.id }}">Deletar</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>Ainda não há sensores registrados!</p>
            {% endif %}
        </div>

            <nav>
                <form action="http://localhost:8080/register_sensor" style="display: inline;">
                    <input type="submit" value="Cadastrar Novo Sensor" />
                </form>
                <form action="http://localhost:8080/home" style="display: inline;">
                    <input type="submit" value="Voltar ao Início" />
                </form>
            </nav>
    </main>
</body>
</html>